name: Generate Snake

# Controls when the action will run
on:
  schedule: # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

# This job runs the snake generator script
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: rajsupratik
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
